### ISSUE TITLE
🚀 Roadmap to MVP

### ISSUE THREAD

**Issue by ixahmedxi** [noodle-run/noodle#327]
Noodle's current objective is to get to an MVP state where we can launch a beta to test it out with users and get feedback. But there is a lot of work to do still to get to that stage.

### MVP Features
We are limiting the features that we will implement for the MVP as that we do not have the capacity to implement the entirety of Noodle's planned features in one go, and so MVP will include:

- Modules
- Tasks
- Notebooks
- Flashcards

#### Modules page
- [ ] Add a button for an alternative way to create a module (💅 Needs design)
- [ ] Make it responsive

#### Task management dashboard & per module task management page
Needs design, feedback to needs & requirements of this feature needed.

#### Flashcards page
Needs design, feedback to needs & requirements of this feature needed.

#### Module page
Instead of putting it in checkboxes, I will firstly give out what I imagine this page to look like and we can get feedback on this. My idea is that Noodle will have a lot of features and possibly even more as we go into the future, and thus creating this page in a way that we can easily accommodate this necessity is vital for us to not need to re-write/design this page and it's layout.

My thinking behind this page or rather inspiration comes from github's repository layout, where there are many features and they are laid out in a beautiful way to accommodate this need and I think this approach also works for us really well. if you have other suggestions please let me know and then we can work on organising how this page will come together in a more organised manner.
![Home Dashboard](https://github.com/ixahmedxi/noodle/assets/20271968/2bc7738a-9f20-4c28-81bf-d0dc9f4f2768)

#### Editor & Notebook page

![Note taking page](https://github.com/ixahmedxi/noodle/assets/20271968/892c57ff-41c6-43f9-8192-8bbed4ce12d9)

The editor is being build using slatejs and platejs.

- [ ] Drag & Drop blocks
- [ ] Toolbar
- [ ] Slash commands
- [ ] Toolbar on selection of text
- [ ] More elements such as code blocks with syntax highlighting
- [ ] More leafs such as highlight
- [ ] Media management (with image upload possibly through uploadThing)
- [ ] Trailing space plugin (this would solve the problem if you have a code leaf at the end of the block, needing to get out of it)
- [ ] Table of contents plugin (just need to get the data using this and then we can display it in a box beside the editor)
- [ ] Notebook saving to db (schema is already made)
- [ ] Generate flashcards from the content of the editor using AI and save it to DB (schema not yet made)
- [ ] Create an AI chatbot that gets the context of the current editor and you can ask it questions about your notebook (design needed)
- [ ] Function in slash commands that would suggest tasks based on the notebook and then the user can choose to add them to their todo list.

There are probably more stuff i'm missing with the editor but I will keep adding on here.

#### Main Dashboard

- [ ] Recent notebooks area with a grid and a list view options.
- [ ] Side area with the weather conditions and tasks for the day
- [ ] Make it responsive (💅 Needs design)

**Comment by luizfranzon** [comment]
OMG, it's so cool! I'm looking forward to trying it!

**Comment by jschoder** [comment]
I have a suggested solution for the responsive main dashboard. Unfortunately there isn't a separate ticket I can ask for being assigned. So there wouldn't be a ticket number to commit it to.
