### ISSUE TITLE
Epic: Modules

### ISSUE THREAD

**Issue by ixahmedxi** [noodle-run/noodle#373]
The basis of all things in Noodle are Modules. Modules are like folders/subjects where they own notes, flashcards, tasks...etc.

Scope of change:
- Empty/No Modules dashboard state.
- Loading state.
- Error state.
- Creation of new modules user flow.
- A module page.
- Way of editing the module after creation.
- Archiving the module
- Recent modules on home dashboard

DB Schema:
- id
- name
- description/about
- code
- icon
- color
- archived
- credits (used for the assignment/progression calculation)
- created at
- modified at
- last visited at (for the recent modules feature)

Steps:
- [ ] Add modules to DB schema.
- [ ] Create db utility functions to do actions on modules like create, edit, archive...etc
- [ ] Create UI state of empty, loading, error.
- [ ] Create UI user flow of creating a new module.
- [ ] Create recent module UI part with empty / loading / error states.
- [ ] Design and create module page.
- [ ] Create user flows of editing / archiving modules (probably going to be on the module page itself).
